#!/usr/bin/env perl

use strict;
use warnings;

my $PERL5_LIB_PATH = "~/perl5";

my @DEPS = qw/
    Bot::BasicBot
    Devel::Cover
    Pod::Coverage
    Redis
    Test::MockModule
    Test::MockObject
/;

for my $dep (@DEPS) {
    system("cpanm -L $PERL5_LIB_PATH $dep");
}
